""" Models for managing purchases """

import datetime
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.db.models import F, FloatField, Sum
from django.conf import settings
from django_userforeignkey.models.fields import UserForeignKey

from product.models import ProductInstance
from purchases.formatChecker import ContentTypeRestrictedFileField


def docs_directory_path(filename):
    """  file will be uploaded to MEDIA_ROOT/projects/user_<id>/Year/Month/<filename> """
    return 'archive/{0}/{1}/{2}'\
        .format(datetime.datetime.now().year, datetime.datetime.now().month, filename)


class Order(models.Model):
    """ Abstract Model contains Orders """
    customer = models.ForeignKey(User, verbose_name=_('Customer'), blank=True, null=True, on_delete=models.PROTECT)
    invoice_number = models.CharField(_('Invoice number'), max_length=45)
    invoice_date = models.DateField(_('Invoice date'), default=datetime.date.today)
    products = models.ManyToManyField(ProductInstance, through='InvoiceLine', related_name='products',
                                      verbose_name=_('Goods'), blank=True)
    comment = models.TextField(_('Comment'), blank=True)
    # Creator and Date information
    created_by = UserForeignKey(auto_user_add=True, verbose_name=_('Created by'))
    date_created = models.DateTimeField(_("Date created"), auto_now_add=True)
    date_updated = models.DateTimeField(_("Date updated"), auto_now=True, db_index=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.invoice_number

    def value_total(self):
        """ return calculated from invoice_lines purchase value"""
        return self.invoiceline_set.aggregate(total_value=Sum(F('quantity')*F('price'),
                                                              output_field=FloatField()))['total_value']
    value_total.short_description = _('Calculated invoice value')

    @classmethod
    def invoice_number_generate(cls):
        """ return autogenerated invoice number"""
        today_str = datetime.date.today().strftime('%Y%m%d')
        today_orders_count = cls.objects.filter(invoice_number__startswith=today_str).count()
        return today_str + '-' + str(today_orders_count + 1)
    invoice_number_generate.short_description = _('Generated invoice number')


class Purchase(Order):
    """ Model contains Purchases """

    class Meta:
        verbose_name = _('Purchase')
        verbose_name_plural = _('Purchases')
        ordering = ['-date_created', '-invoice_number']


class Sale(models.Model):
    """ Model contains Sales, Baskets """
    InBasket = 'IB'
    NewOrder = 'NO'
    Cancelled = 'CN'
    Confirmed = 'CF'
    Sent = 'ST'
    Received = 'RC'
    Returned = 'RT'
    STATUS_CHOICES = (
        (InBasket, _('Products in  basket')),
        (NewOrder, _('New order')),
        (Cancelled, _('Order canceled')),
        (Confirmed, _('Order confirmed')),
        (Sent, _('Order sent')),
        (Received, _('Order received')),
        (Returned, _('Order returned')),
    )
    NotPaid = 'NP'
    AdvancePaid = 'AP'
    PaidUp = 'PU'
    PAYMENT_STATUS_CHOICES = (
        (NotPaid, 'Не оплачений'),
        (AdvancePaid, 'Оплачений аванс'),
        (PaidUp, 'Оплачений')
        )
    status = models.CharField(_('Deal type'), max_length=2, choices=STATUS_CHOICES, default=InBasket)
    pay_status = models.CharField('Статус оплати', max_length=2, choices=PAYMENT_STATUS_CHOICES, default=NotPaid)
    value = models.DecimalField(_('Value'), max_digits=8, decimal_places=2, default=0)
    upload = ContentTypeRestrictedFileField(_('Electronic copy'), upload_to=docs_directory_path,
                                            content_types=['application/pdf',
                                                           'application/vnd.openxmlformats-officedocument'
                                                           '.spreadsheetml.sheet',
                                                           'application/vnd.openxmlformats-officedocument'
                                                           '.wordprocessingml.document'],
                                            max_upload_size=26214400,
                                            blank=True, null=True)
    arrival_date = models.DateField(_('Arrival date'), default=datetime.date.today)

    class Meta:
        verbose_name = _('Purchase')
        verbose_name_plural = _('Purchases')
        ordering = ['-date_created', '-invoice_number']


class InvoiceLine(models.Model):
    """ Model contains InvoiceLines for Purchases model """
    product = models.ForeignKey(Product, verbose_name=_('Goods'), on_delete=models.PROTECT)
    purchase = models.ForeignKey(Purchase, verbose_name=_('Purchase'), on_delete=models.PROTECT)
    quantity = models.PositiveSmallIntegerField(_('Amount'), default=1)
    unit_price = models.DecimalField(_('Unit price'), max_digits=8, decimal_places=2, default=0)

    def value_total(self):
        """ return calculated invoice_line value"""
        return self.unit_price * self.quantity
    value_total.short_description = _('Calculated invoice_line value')
