# Generated by Django 2.2.8 on 2020-01-07 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Cylinder',
                'verbose_name_plural': 'Cylinders',
            },
        ),
        migrations.CreateModel(
            name='DiopterPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Diopter Power',
                'verbose_name_plural': 'Diopter Powers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('short_description', models.TextField(blank=True, verbose_name='Product description')),
                ('long_description', models.TextField(blank=True, verbose_name='Product description')),
                ('product_image', models.ImageField(upload_to='Product/image', verbose_name='Product image')),
                ('brand_name', models.CharField(max_length=32, unique=True, verbose_name='Brand name')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Brand Image')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-date_created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Product price')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Cylinder')),
                ('diopter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.DiopterPower')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Product Instance',
                'verbose_name_plural': 'Product Instances',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_hand', models.IntegerField(verbose_name='Quantity in hand')),
                ('product_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductInstance', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
