# Generated by Django 2.2.8 on 2020-01-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='date_updated',
        ),
    ]
