# Generated by Django 2.2.8 on 2020-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200119_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='footer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site footer'),
        ),
    ]
