# Generated by Django 2.2.8 on 2020-01-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200120_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cylinder',
            options={'ordering': ['id'], 'verbose_name': 'Cylinder', 'verbose_name_plural': 'Cylinders'},
        ),
        migrations.AlterModelOptions(
            name='diopterpower',
            options={'ordering': ['id'], 'verbose_name': 'Diopter Power', 'verbose_name_plural': 'Diopter Powers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['id'], 'verbose_name': 'Product Instance', 'verbose_name_plural': 'Product Instances'},
        ),
    ]
