# Generated by Django 2.2.8 on 2020-01-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200115_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='quantity_in_hand',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity in hand'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
