# Generated by Django 2.2.8 on 2020-01-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200115_1119'),
        ('product', '0004_auto_20200115_0957'),
    ]

    operations = [
    ]
