# Generated by Django 2.2.8 on 2020-01-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoiceline',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
