# Generated by Django 2.2.8 on 2020-01-20 10:19

from django.db import migrations, models
import purchase.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=purchase.models.docs_directory_path, verbose_name='Download Invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'Products in cart'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('ST', 'Order sent'), ('RT', 'Order returned')], default='IC', max_length=2, verbose_name='Order status'),
        ),
    ]
