# Generated by Django 2.2.8 on 2020-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200110_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'Products in cart'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('ST', 'Order sent'), ('RC', 'Order received'), ('RT', 'Order returned')], default='IC', max_length=2, verbose_name='Deal type'),
        ),
    ]
