# Generated by Django 2.2.8 on 2020-01-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200120_1219'),
        ('purchase', '0004_auto_20200120_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='cylinder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.Cylinder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='diopter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.DiopterPower'),
            preserve_default=False,
        ),
    ]
