# Generated by Django 2.2.8 on 2020-01-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200120_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created', 'invoice_number'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
