# Generated by Django 2.2.8 on 2020-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200115_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'Products in cart'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('RT', 'Order returned')], default='IC', max_length=2, verbose_name='Deal type'),
        ),
    ]
