# Generated by Django 2.2.8 on 2020-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20200115_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IC', 'Products in cart'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('RT', 'Order returned')], default='IC', max_length=2, verbose_name='Order status'),
        ),
    ]
