# Generated by Django 2.2.8 on 2020-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20200121_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_status',
            field=models.CharField(choices=[('IC', 'Products in cart'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('ST', 'Order sent'), ('RT', 'Order returned')], default='IC', max_length=2),
        ),
    ]
