# Generated by Django 2.2.8 on 2020-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_order_old_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='value',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='old_status',
            field=models.CharField(choices=[('IC', 'Products in cart'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('ST', 'Order sent'), ('RT', 'Order returned')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comment'),
        ),
    ]
