# Generated by Django 2.2.8 on 2020-01-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20200128_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_date',
        ),
    ]
