# Generated by Django 2.2.8 on 2020-01-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_remove_order_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='invoice_date',
        ),
    ]
