# Generated by Django 2.2.8 on 2020-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20200204_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lenses_sum',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Sum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
    ]
