# Generated by Django 2.2.8 on 2020-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20200214_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lenses_sum',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sum'),
        ),
    ]
