# Generated by Django 2.2.10 on 2020-04-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_20200430_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set(),
        ),
    ]
